version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_DATABASE=hydrate
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - hydrate-net

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hydrate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hydrate-net

networks:
  hydrate-net:

volumes:
  postgres_data: