version: '3.9'

services:
  # Layanan Backend Aplikasi
  backend:
    # Menentukan nama image dan tag yang akan dibuat
    image: ${POSTGRES_USER}/hydrate-backend:dev
    container_name: hydrate_backend_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    
    ports:
      # Memetakan port dari .env ke port internal 3000
      - "${PORT}:3000"
    env_file:
      - ./.env # Memuat semua variabel dari .env ke dalam kontainer
    networks:
      - hydrate-net
    depends_on:
      - db
      - redis

  # Layanan Database PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: hydrate_postgres
    restart: always
    env_file:
      - ./.env
    environment:
      # Membaca kredensial dari file .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hydrate-net

  # Layanan Caching Redis
  redis:
    image: redis:7-alpine
    container_name: hydrate_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - hydrate-net

# Mendefinisikan jaringan kustom untuk semua layanan
networks:
  hydrate-net:
    driver: bridge

# Mendefinisikan volume untuk persistensi data
volumes:
  postgres_data:
  redis_data: